=== dmitriysedin/EPAM-JWD23-TASK03WEB/resources/restaurant_perl_menu_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.dmitriysedin.by/epam/jwd23/task03"
        xmlns:tns = "http://www.dmitriysedin.by/epam/jwd23/task03">
    <element name="menues" type="tns:menuesType"/>
    <complexType name="menuesType">
        <sequence>
            <element name="menu" type="tns:menuType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="menuType">
        <sequence>
            <element name="menu-name" type="string" default="Основное меню"/>
            <element name="menu-annotation" type="string" minOccurs="0"/>
            <element name="assortment" type="tns:assortmentType" maxOccurs="unbounded">
            </element>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="currency" type="string" use="required"/>
    </complexType>
    <complexType name="assortmentType">
        <sequence>
            <element name="assortment-name" default="Основной ассортимент">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Основной ассортимент"/>
                        <enumeration value="Холодные закуски"/>
                        <enumeration value="Горячие закуски"/>
                        <enumeration value="Завтраки"/>
                        <enumeration value="Салаты"/>
                        <enumeration value="Супы"/>
                        <enumeration value="Рыбные блюда"/>
                        <enumeration value="Мясные блюда"/>
                        <enumeration value="Гарниры"/>
                        <enumeration value="Блюда на мангале"/>
                        <enumeration value="От шеф-повара"/>
                        <enumeration value="Приложение"/>
                        <enumeration value="Десерт"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="assortment-annotation" type="string" minOccurs="0"/>
            <element name="dish" type="tns:dishType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>
    <complexType name="dishType">
        <sequence>
            <element name="dish-name" type="string"/>
            <element name="dish-annotation" type="string" minOccurs="0"/>
            <element name="dish-extra-description" type="string" minOccurs="0"/>
            <element name="dish-specification" type="tns:dishSpecificationType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>
    <complexType name="dishSpecificationType">
        <sequence>
            <element name="dish-description" type="string" minOccurs="0"/>
            <element name="dish-portion" type="string"/>
            <element name="dish-price" type="string"/>
        </sequence>
    </complexType>
</schema>

=== dmitriysedin/EPAM-JWD23-TASK03WEB/WebContent/resources/restaurant_perl_menu.xml
<?xml version="1.0" encoding="UTF-8" ?>

<myns:menues
	xmlns:myns="http://www.dmitriysedin.by/epam/jwd23/task03"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dmitriysedin.by/epam/jwd23/task03 restaurant_perl_menu_schema.xsd">
	<menu id="menu01" currency="рубль">
		<menu-name>Основное меню</menu-name>
		<menu-annotation>Ежедневное основное меню</menu-annotation>
		<assortment id="assortment01">
			<assortment-name>Холодные закуски</assortment-name>
			<assortment-annotation>Не менее 20 блюд</assortment-annotation>
			<dish id="dish01">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Ассорти баклажаны</dish-name>
				<dish-annotation>Имеются 3 варианта исполнения</dish-annotation>
				<dish-extra-description>Жареные баклажаны с помидорами</dish-extra-description>
				<dish-specification>
					<dish-description>1. с помидорами</dish-description>
					<dish-portion>100/5</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
				<dish-specification>
					<dish-description>2. с чесноком</dish-description>
					<dish-portion>100/5</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
				<dish-specification>
					<dish-description>3. с орехами</dish-description>
					<dish-portion>100/5</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish02">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Ассорти рыбное</dish-name>
				<dish-specification>
					<dish-description>Слабосоленая форель, семга</dish-description>
					<dish-portion>100/20/15</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish09">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Тарталетки с красной икрой</dish-name>
				<dish-specification>
					<dish-description>Тарталетки с красной икрой</dish-description>
					<dish-portion>60/50</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish10">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Бастурма</dish-name>
				<dish-specification>
					<dish-description>Вяленая вырезка из говяжьего мяса</dish-description>
					<dish-portion>50/5</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish11">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Брынза</dish-name>
				<dish-specification>
					<dish-description>Рассольный сыр, изготавливаемый из овечьего молока</dish-description>
					<dish-portion>75/5</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish03">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Лимон</dish-name>
				<dish-specification>
					<dish-portion>100/20/15</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
		</assortment>
		<assortment id="assortment2">
			<assortment-name>Горячие закуски</assortment-name>
			<assortment-annotation>Не менее 5 блюд</assortment-annotation>
			<dish id="dish04">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Жульен</dish-name>
				<dish-specification>
					<dish-description>1. с курицей</dish-description>
					<dish-portion>120/1</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
				<dish-specification>
					<dish-description>2. с грибами</dish-description>
					<dish-portion>120/1</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish05">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Лобио с шампиньонами</dish-name>
				<dish-specification>
					<dish-description>Фасоль с шампиньонами и грецким орехом</dish-description>
					<dish-portion>150/5</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish06">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Сюрприз</dish-name>
				<!-- вставить ссылку на фото -->
				<dish-specification>
					<dish-portion>1 шт</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
		</assortment>
		<assortment id="assortment3">
			<assortment-name>Завтраки</assortment-name>
			<assortment-annotation>Не менее 3 блюд, подаются до 11-00 в будние дни</assortment-annotation>
			<dish id="dish07">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Глазунья</dish-name>
				<dish-specification>
					<dish-description>2 яйца (на выбор: ветчина, сыр, помидоры)</dish-description>
					<dish-portion>150</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
			<dish id="dish08">
				<dish-photo>photo.jpg</dish-photo>
				<dish-name>Омлет</dish-name>
				<dish-specification>
					<dish-portion>100</dish-portion>
					<dish-price>10</dish-price>
				</dish-specification>
			</dish>
		</assortment>
	</menu>
</myns:menues>
